SELECT 
    B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
LEFT OUTER JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
LEFT OUTER JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE < '2022-02-01'
GROUP BY 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, 
    B.CATEGORY DESC;
