SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP JOIN FOOD_ORDER FO
  ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC ,PRODUCT_ID ASC;