SELECT FH.FLAVOR
FROM FIRST_HALF FH
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JU ON FH.FLAVOR = JU.FLAVOR
ORDER BY FH.TOTAL_ORDER + IFNULL(JU.JULY_TOTAL_ORDER, 0) DESC
LIMIT 3;
